/* 业务决策主线。人工记录与模型报告分开，关系通过机会卡 id 保存。 */
const BUSINESS_FIELDS={
 brief:[['product','产品 / 服务'],['market','目标市场与渠道'],['goal','这次要解决的营销问题'],['constraints','业务限制与已有条件'],['success','什么结果算有帮助']],
 opportunity:[['title','需求机会名称'],['scenario','发生在什么场景'],['task','消费者想完成什么任务'],['obstacle','卡在哪里'],['alternative','目前怎么解决 / 竞品如何表达'],['gap','仍未满足的部分'],['evidence','支持原文、来源编号或链接（待核对）']],
 strategy:[['audience','优先服务哪类人'],['reason','为什么优先：需求证据 × 产品承接 × 竞争差异'],['promise','向这类人承诺什么改变'],['proof','我们能拿出什么证明'],['avoid','不服务的场景 / 不应承诺的内容']],
 content:[['title','内容选题'],['angle','表达角度：针对当前人群的哪个问题'],['outline','开头与内容提纲'],['proof','需要制作或补充的证明材料'],['metric','准备观察什么反馈，怎样判定']],
 feedback:[['observation','实际观察到什么'],['source','日期、样本范围、来源或结果链接'],['result','验证结论'],['next','下一轮调整什么']]
};
const businessDrafts={};
function businessData(){return state.project?.decision_workspace||{brief:{},cases:[],selected_id:''}}
function selectedOpportunity(){const w=businessData();return w.cases.find(x=>x.id===w.selected_id)||null}
function businessDraftKey(kind){return [state.project?.id,kind,kind==='brief'?'':selectedOpportunity()?.id||'new'].join(':')}
function businessForm(kind,value){const data=businessDrafts[businessDraftKey(kind)]||value||{};return `<form class="business-form" data-business-form="${kind}"><div class="business-fields">${BUSINESS_FIELDS[kind].map(([key,label])=>`<label>${esc(label)}${key==='result'?`<select name="${key}">${['未验证','支持当前假设','不支持当前假设','结果不明确'].map(x=>`<option ${x===data[key]?'selected':''}>${x}</option>`).join('')}</select>`:`<textarea name="${key}" rows="${key==='title'?2:3}" maxlength="4000">${esc(data[key]||'')}</textarea>`}</label>`).join('')}</div><div class="actions">${button('保存'+({brief:'项目目标',opportunity:'机会卡',strategy:'人群策略',content:'内容方案',feedback:'验证记录'}[kind]),'save-business','','primary',`data-kind="${kind}" type="button"`)}<span class="caption">手工记录 · 保存到本机项目；未保存的输入在当前页面会话暂存。</span></div></form>`}
function businessSelectedContext(c){return `<div class="audience-context"><div><span class="eyebrow">当前需求机会 · ${esc(c.id)}</span><h2>${esc(c.title)}</h2><p>${esc(c.scenario||'场景待补充')} · ${esc(c.task||'任务待补充')}</p></div>${button('切换 / 编辑机会','navigate','','small','data-page="opportunities"')}</div>${c.source_version!==state.project.data_version?'<p class="source-note">原始资料已更新；这张机会卡仍基于旧版本，请复核证据后更新。</p>':''}`}
function opportunitySources(){const r=latestKeywordClassification(true);if(!r)return '<p class="caption">尚无七步清洗报告。可先查看研究资料，也可以依据已有原文手工创建机会。</p>';const themes=[...new Set((r.report.items||[]).filter(x=>x.valid===true).map(x=>x.theme).filter(Boolean))];return `<details class="report-details"><summary>从已有清洗主题建立机会草稿（${themes.length} 个主题）</summary>${reportMeta(r)}${themes.map((theme,i)=>`<article class="finding"><h3>${esc(theme)}</h3><p>主题只是线索；场景、任务和机会缺口需要继续填写依据。</p>${button('以此主题起草机会','theme-opportunity','','small',`data-theme-index="${i}" ${r.data_version!==state.project.data_version?'disabled':''}`)}</article>`).join('')}</details>`}
function businessWorkspace(){
 const p=state.project,w=businessData(),c=selectedOpportunity(),page=state.page;
 const intro={brief:['项目目标','先说清这次要做哪个营销判断，不要求每个项目都从采词开始。'],materials:['研究资料','围绕项目问题补充证据。采词、清洗、评论和竞品都是工具，不是最终结论。'],opportunities:['需求机会','把词和原文整理成“场景—任务—障碍—缺口”，再决定值得服务谁。'],strategy:['人群策略','围绕选中的需求机会，做优先人群与差异化取舍。'],content:['内容方案','把当前机会和人群策略交给创作者：为谁讲、讲什么、用什么证明。'],feedback:['验证复盘','用实际观察检验这一版内容和策略；没有真实反馈就保留未验证。']}[page];
 let body='';
 if(page==='brief')body=businessForm('brief',w.brief)+`<div class="next-step"><div><h3>带着问题准备资料</h3><p>已有报告或原始词也可以直接进入研究资料，不必重采。</p></div>${button('准备研究资料','navigate','','primary','data-page="materials"')}</div>`;
 if(page==='materials')body=`<section class="report-sheet"><h2>这次要回答的问题</h2><p>${esc(w.brief?.goal||'尚未填写项目目标，可以先补目标，也可以查看已有资料。')}</p><div class="business-tool-grid">${[['research','采下拉词 / 查看原文',p.keywords.length+' 条关键词 · '+(p.posts||[]).length+' 篇内容 · '+p.reviews.length+' 条评论'],['keywords','七步清洗关键词','保留原词、排除原因与主题'],['products','竞品与替代方案','比较别人如何解决问题，不进入选品主线'],['insights','模型分析与历史报告','查阅已有分析；点击生成才使用模型']].map(([route,title,desc])=>`<article><h3>${title}</h3><p>${esc(desc)}</p>${button('打开工具','navigate','','small',`data-page="${route}"`)}</article>`).join('')}</div></section><div class="next-step"><div><h3>从资料形成需求机会</h3><p>关键词清洗结果只是线索，深层动机与商业机会仍需证据支持。</p></div>${button('整理需求机会','navigate','','primary','data-page="opportunities"')}</div>`;
 if(page==='opportunities')body=opportunitySources()+`<div class="section-head"><h2>机会池 · ${w.cases.length} 张</h2>${button('新建机会卡','new-opportunity','','primary')}</div><div class="audience-candidates">${w.cases.map(x=>`<article class="report-sheet"><span class="eyebrow">手工整理 · ${x.id===w.selected_id?'当前选中':'候选机会'}</span><h2>${esc(x.title)}</h2><p>${esc(x.scenario||'场景待补充')}</p><p>${esc(x.task||'消费者任务待补充')}</p><p class="caption">人群：${esc(x.strategy?.audience||'尚未确定')} · 反馈：${esc(x.feedback?.result||'未验证')}</p>${button('选择并制定策略','select-opportunity','','primary',`data-id="${esc(x.id)}"`)}</article>`).join('')}</div>${c?businessSelectedContext(c):'<p class="source-note">新建一张机会卡。只填写有依据的观察，缺少依据的内容保留待验证。</p>'}${businessForm('opportunity',c)}`;
 if(['strategy','content','feedback'].includes(page)){
  if(!c)body=empty('先选择一张需求机会卡','后续策略、内容和反馈通过同一个机会编号关联，不自动拼接不相关的报告。',button('前往需求机会','navigate','','primary','data-page="opportunities"'));
  else {
   body=businessSelectedContext(c);
   if(page==='strategy')body+=`<details class="report-details"><summary>查看机会证据与现有解决办法</summary><p>${esc(c.evidence||'暂无支持证据，当前为待验证假设')}</p><p>现有办法：${esc(c.alternative)}</p><p>机会缺口：${esc(c.gap)}</p></details>${businessForm('strategy',c.strategy)}<details class="report-details"><summary>辅助分析：千机塔、搜索意图与历史画像</summary><p>这些工具用于补充判断，不会自动替代当前机会卡的人工取舍。</p>${button('查看人群分析','navigate','','small','data-page="audience"')}${button('查看千机塔','navigate','','small','data-page="tower"')}</details>${button('继续制定内容方案 →','navigate','','primary','data-page="content"')}`;
   if(page==='content')body+=`<section class="report-sheet"><h2>沿用的人群与承诺</h2><p>为谁：${esc(c.strategy?.audience||'尚未保存人群策略')}</p><p>承诺：${esc(c.strategy?.promise||'待确定')}</p><p>证明：${esc(c.strategy?.proof||'待补充')}</p></section>${businessForm('content',c.content)}${button('记录真实验证 →','navigate','','primary','data-page="feedback"')}`;
   if(page==='feedback'){const changed=c.feedback?.context&&c.feedback.context!==JSON.stringify([c.strategy,c.content]);body+=`<section class="report-sheet"><h2>本次验证对象</h2><p>人群：${esc(c.strategy?.audience||'待确定')} · 内容：${esc(c.content?.title||'待确定')}</p><p>预定观察标准：${esc(c.content?.metric||'尚未填写')}</p>${changed?'<p class="source-note">策略或内容在上次记录反馈后发生变化；旧反馈不代表新版已验证。</p>':''}<p class="caption">这里记录人工反馈，不自动读取投放或成交数据，也不把相关性当作因果。</p></section>${businessForm('feedback',c.feedback)}${button('返回策略做下一轮调整','navigate','','','data-page="strategy"')}`;}
  }
 }
 return head(intro[0],intro[1],button('导出决策记录','export-business','download','small'))+flowNav(page)+demoNote()+body;
}
async function saveBusinessWorkspace(w){const projectId=state.project.id;const result=await api('/api/projects/'+projectId+'/decision-workspace',{revision:state.project.revision,workspace:w});if(state.project?.id===projectId){state.project=result;render()}return result}
async function businessAction(action,el){
 if(action==='save-business'){
  const kind=el.dataset.kind,form=el.closest('form'),data=Object.fromEntries(BUSINESS_FIELDS[kind].map(([key])=>[key,form.elements.namedItem(key).value]));
  const w=JSON.parse(JSON.stringify(businessData())),draftKey=businessDraftKey(kind);el.disabled=true;
  try{if(kind==='brief')w.brief=data;else if(kind==='opportunity'){if(!data.title.trim())throw Error('请填写需求机会名称');let c=w.cases.find(x=>x.id===w.selected_id);if(!c){c={id:'opp-'+crypto.randomUUID(),strategy:{},content:{},feedback:{}};w.cases.push(c);w.selected_id=c.id}Object.assign(c,data,{source_version:state.project.data_version});}else{const c=w.cases.find(x=>x.id===w.selected_id);if(!c)throw Error('请先选择机会');if(kind==='feedback')data.context=JSON.stringify([c.strategy,c.content]);c[kind]=data}await saveBusinessWorkspace(w);delete businessDrafts[draftKey];toast('已保存到当前项目');}finally{el.disabled=false}return true;
 }
 if(action==='select-opportunity'){const w=JSON.parse(JSON.stringify(businessData()));if(!w.cases.some(x=>x.id===el.dataset.id))throw Error('机会不存在');w.selected_id=el.dataset.id;const projectId=state.project.id;await saveBusinessWorkspace(w);if(state.project?.id===projectId)goto('strategy');return true}
 if(action==='new-opportunity'){const w=JSON.parse(JSON.stringify(businessData()));w.selected_id='';await saveBusinessWorkspace(w);return true}
 if(action==='theme-opportunity'){const r=latestKeywordClassification(true);if(!r||r.data_version!==state.project.data_version)throw Error('请先更新清洗报告');const items=(r.report.items||[]).filter(x=>x.valid===true),themes=[...new Set(items.map(x=>x.theme).filter(Boolean))],theme=themes[Number(el.dataset.themeIndex)];if(!theme)throw Error('主题不存在');const draft={title:theme, evidence:items.filter(x=>x.theme===theme).map(x=>x.id+'：'+reportKeyword(r,x.id)).join('\n')};const projectId=state.project.id,w=JSON.parse(JSON.stringify(businessData()));w.selected_id='';await saveBusinessWorkspace(w);if(state.project?.id===projectId){businessDrafts[businessDraftKey('opportunity')]=draft;goto('opportunities')}return true}
 if(action==='export-business'){download('人群策略决策记录.json',JSON.stringify({project:state.project.name,exported_at:new Date().toISOString(),workspace:businessData()},null,2),'application/json');return true}
 return false;
}
document.addEventListener('submit',e=>{if(e.target.matches('[data-business-form]'))e.preventDefault()});
document.addEventListener('input',e=>{const form=e.target.closest?.('[data-business-form]');if(!form)return;const kind=form.dataset.businessForm;businessDrafts[businessDraftKey(kind)]=Object.fromEntries(BUSINESS_FIELDS[kind].map(([key])=>[key,form.elements.namedItem(key).value]))});
