/* Online research and first-use guidance. Uses the workbench's existing UI primitives. */
const PLATFORM_LABELS={tiktok:'TikTok',xhs:'小红书',reddit:'Reddit',amazon:'Amazon'};
let collectionJob=null, collectionPoll=null, collectionKind='posts', collectionPlatform='tiktok', collectionPostIds=[];
async function resumeCollection(){if(!state.project)return;const id=state.project.id;const active=await api('/api/active-jobs');if(state.project?.id!==id)return;const current=active.find(x=>x.project_id===id);if(current){clearTimeout(collectionPoll);collectionJob=current;await pollCollection()}}

function guide(){return head('三个入口，完成一次调研','先了解需求，再核对竞品，最后查看选品依据。',button('进入关键词洞察','navigate','arrow','primary','data-page="research"')+button('体验演示','demo',''))+`<div class="guide-image"><img src="/usage-flow.svg" alt="关键词洞察：采集资料、关键词分析、需求与选品；电商盯盘按需查询；报告与选品查看依据并导出"></div><section class="flat-section"><ol class="guide-list"><li><strong>关键词洞察 · 采集资料。</strong>输入中文产品词，例如「宠物饮水机」，勾选小红书、TikTok、Reddit、Amazon 中的一个或多个平台，选择快速、A～Z 或意图深挖，高级模式可设 1～6 轮与请求上限，再点「采集关键词」。同词多平台保存在同一个项目。</li><li><strong>关键词洞察 · 关键词分析。</strong>采完点「选择洞察内容」，勾选关键词库、意图、人群等本次需要的分析；也可在关键词分析页查看主题与 5W1H；点「返回关键词资料」查看原词。主题地图中的「搜这组词」可继续搜索内容。</li><li><strong>需求与选品 · 形成产品方向。</strong>优先选择「人群画像」「搜索意图」「评论需求」与「选品建议」，先看服务谁、解决什么问题，再提出值得验证的产品方向。需要评论时，跨平台勾选相关内容后点「采集所选评论」；Amazon 商品可点「采商品评论」。在产品方向下点「去卖家精灵查商品」，核对预填关键词和预算后，手动开始查询。「内容规律」「营销选题」仅按需勾选。每项依次保存，失败可单独重跑；点「查看依据」回看原文。</li><li><strong>电商盯盘 · 核对竞品。</strong>查商品、加入关注清单并比较；点击商品后手动读取历史，每次最多 2 次 MCP 查询。价格、排名与评分记录查询近 90 天，月度父子体销量取供应商返回范围，均标明来源。未开启定时监控。</li><li><strong>报告与选品 · 看依据和信息缺口。</strong>点「整理选品依据」，直接查看候选的评价证据与待验证资料。这里也可重新打开关键词分析、需求与选品报告。</li><li><strong>翻译、导出与接续。</strong>英文关键词、内容和评论可翻译成中文，每批最多 20 条，原文保留。单份分析支持 Markdown 和 HTML；完整 HTML 保留选品依据与竞品历史。项目包恢复后可接着使用。</li></ol></section><section class="flat-section"><h2>补充资料后，继续同一项目</h2><p>原文、中文译文和报告都保存在项目中；通过顶部切换项目。补采后旧报告保留并提示更新，分析失败会显示原因。</p><p>分析与翻译调用本机已登录的 Codex，无需另填模型密钥；样本仍会发送到 Codex 模型服务。</p><p class="caption">小红书讨论不能直接代表美国消费者；关键词数量不代表搜索量。人群和隐性动机属于待验证推断，销量为供应商估算，报告会显示实际样本范围。</p></section>`}

function jobView(){if(!collectionJob||collectionJob.project_id!==state.project?.id)return '';const r=collectionJob.run;const names=(r.platforms||[r.platform]).map(x=>PLATFORM_LABELS[x]||x).join('、');return `<div class="collection-progress" role="status" aria-live="polite"><div><strong>${esc(names)} · ${{keywords:'关键词',posts:'内容与商品',reviews:'评论采集'}[r.kind]||r.kind} · ${{running:'采集中',success:'已完成',partial:'部分完成',failed:'失败',cancelled:'已取消'}[r.status]||r.status}${r.keyword_mode?' · '+esc(KEYWORD_MODE_LABELS[r.keyword_mode])+' · 第 '+r.current_round+' / '+r.rounds+' 轮':''}</strong><p>已发出 ${r.requests} / ${r.request_limit} 次请求 · 成功 ${r.pages} 页 · 新增 ${r.imported} 条 · 重复 ${r.duplicates} 条 · 异常 ${r.errors.length} 项</p>${r.platform_results?.length?`<div class="platform-progress">${r.platform_results.map(x=>`<span>${esc(PLATFORM_LABELS[x.platform])}：${{pending:'等待',running:'采集中',success:'完成',partial:'部分完成',failed:'失败',cancelled:'已取消'}[x.status]||x.status} · ${x.imported} 条</span>`).join('')}</div>`:''}${r.translations?.length?'<p>'+r.translations.map(x=>esc(x.original)+' → '+esc(x.translated)+'（机器翻译）').join('；')+'</p>':''}${r.capped?'<p class="caption">已达到本次请求上限，结果已保存；尚未完成的扩词不会继续请求。</p>':''}</div><div class="actions">${r.status==='running'?button('停止采集','cancel-collection','','small'):''}${button('查看详情','collection-detail','','small')}</div></div>`}

function posts(){const p=state.project;let rows=(p.posts||[]).filter(r=>(r.title+' '+r.body+' '+r.query).toLowerCase().includes(state.query.toLowerCase())&&(state.filter==='all'||r.platform===state.filter));return head('内容与评论','先按词搜索，再选择相关内容采集评论。所有原文都保留来源。',button('搜索内容','open-search','search','primary'))+flowNav('posts')+demoNote()+jobView()+aiProgress()+`<div class="toolbar"><div class="search">${icon('search')}<input id="search-input" aria-label="筛选已保存内容" placeholder="筛选已保存内容或搜索词" value="${esc(state.query)}"></div><select id="filter-select" aria-label="内容平台"><option value="all">全部平台</option>${Object.entries(PLATFORM_LABELS).map(([k,v])=>`<option value="${k}" ${state.filter===k?'selected':''}>${v}</option>`).join('')}</select><div class="spacer"></div>${button('翻译内容','translate-posts','','small')}${button('选择洞察内容','navigate','arrow','small','data-page="insights"')}</div><div class="selection-bar"><span>已选 ${state.selected.size} 条内容 · 可以跨平台选择</span>${button('采集所选评论','collect-selected','chat','small',state.selected.size?'':'disabled')}</div>${rows.length?`<div class="table-wrap"><table class="posts-table"><colgroup><col style="width:40px"><col><col style="width:80px"><col style="width:100px"><col style="width:72px"><col style="width:90px"></colgroup><thead><tr><th><input type="checkbox" id="select-all" aria-label="选择当前内容"></th><th>内容 / 来源关键词</th><th>平台</th><th>平台互动数</th><th>已采评论</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td><input type="checkbox" data-select="${esc(r.id)}" ${state.selected.has(r.id)?'checked':''} aria-label="选择 ${esc(r.title)}"></td><td style="max-width:440px"><button class="post-title" data-action="post-detail" data-id="${esc(r.id)}">${esc(r.title)}</button>${r.translation?`<div class="translation-preview">${esc(r.translation)}</div>`:''}<div class="secondary">搜索词：${esc(r.query)} · ${date(r.collected_at)}</div></td><td>${badge(PLATFORM_LABELS[r.platform])}<div class="secondary">${source(r)}</div></td><td><span>${r.likes??'—'} ${r.platform==='reddit'?'得分':'赞'}</span><div class="secondary">${r.comment_count??'—'} 条评论</div></td><td>${p.reviews.filter(c=>c.post_id===r.id).length}</td><td>${button('评论','post-comments','chat','small',`data-id="${esc(r.id)}"`)}<div class="secondary">${external(r.source_url,'原帖')}</div></td></tr>`).join('')}</tbody></table></div><div class="table-footer">${rows.length} / ${p.posts.length} 条内容 · 评论数为平台返回值，包含的回复层级可能与已采样本不同</div>`:empty('从相关讨论开始','例如：TikTok / Reddit 搜 portable blender；小红书搜「便携榨汁杯」。海外平台支持输入中文后自动翻译。',button('按关键词搜索内容','open-search','search','primary'))}<p class="bottom-note">TikTok 使用 US 搜索区域，Reddit 为全站搜索；用户实际地域均未确认。小红书为中文平台讨论。社交评论不等于已购评价；本版不补抓全部楼中楼。</p>`}

function collectModal(kind,query='',platform=['xhs','tiktok','reddit'],postIds=[]){
 if(!state.project){runAction('new',{});return}
 if(state.project.demo){modal('开始真实调研',`<p>当前是虚构演示项目。新建真实项目后，就能采集关键词、内容和评论。</p>`,button('取消','close')+button('新建真实项目','new','','primary'));return}
 collectionKind=kind;collectionPostIds=postIds;
 let platforms=Array.isArray(platform)?platform:[platform];platforms=platforms.filter(x=>PLATFORM_NAMES[x]);if(!platforms.length)platforms=['xhs','tiktok','reddit'];collectionPlatform=platforms;
 modal({keywords:'多平台采集关键词',posts:'用关键词搜索内容与商品',reviews:'采集所选内容的评论'}[kind],`${kind==='reviews'?`<p>已选择 ${postIds.length} 条内容，平台由原帖自动识别。逐条采集并保存。</p>`:`<div class="field"><label>平台 · 可多选</label>${platformPicker('collect-platform',platforms)}</div><div class="field"><label for="collect-queries">${kind==='keywords'?'产品关键词':'搜索关键词'} · 每行一个</label><textarea id="collect-queries" rows="4" placeholder="宠物饮水机\n宠物饮水机清洗">${esc(query||state.project.keyword)}</textarea></div>`}${kind==='keywords'?keywordControls('collect',quick):''}<div class="field" ${kind==='keywords'?'hidden':''}><label for="collect-pages">${kind==='reviews'?'每条内容':kind==='posts'?'每个关键词':'关键词'}采集页数</label><select id="collect-pages" ${kind==='keywords'?'disabled':''}>${(kind==='keywords'?[1]:[1,2,3,5,10]).map(v=>`<option value="${v}">${v} 页${v===1?'（首次推荐）':''}</option>`).join('')}</select></div><div class="callout" id="collect-budget"></div><p class="caption">Amazon 每词固定 1 页、最多 10 条，使用 MCP 会员次数。其他平台使用 TikHub 余额；中文查询只翻译一次并复用。单个平台失败，其他平台继续保存。${kind==='keywords'?'快速最多 20 次；A～Z 与意图深挖最多 500 次，以填写上限为准。':'每次最多 20 个请求。'}</p>`,button('取消','close')+button('开始采集并保存','start-collection','search','primary'));
 updateBudget();
}
function collectPlatforms(){return [...document.querySelectorAll('input[name="collect-platform"]:checked')].map(x=>x.value)}
function updateBudget(){const target=document.querySelector('#collect-budget');if(!target)return;const queries=[...new Set((document.querySelector('#collect-queries')?.value||'').split('\n').map(x=>x.trim()).filter(Boolean))];const pages=Number(document.querySelector('#collect-pages').value);const platforms=collectPlatforms();if(collectionKind==='keywords'){try{target.textContent=keywordBudgetText(readKeywordControls('collect'),queries,platforms)}catch(error){target.textContent=error.message}return}const translation=collectionKind!=='reviews'&&platforms.some(x=>x!=='xhs')?queries.filter(x=>/[\u3400-\u9fff]/.test(x)).length:0;const tik=collectionKind==='reviews'?collectionPostIds.length*pages:queries.length*platforms.filter(x=>x!=='amazon').length*pages+translation;const mcp=collectionKind==='reviews'?0:queries.length*(platforms.includes('amazon')?1:0);target.textContent=`最多 ${tik+mcp} 次请求：TikHub ${tik} 次（保守约 US$${(tik*.01).toFixed(2)}）${mcp?'，卖家精灵 '+mcp+' 次查询':''}。${tik+mcp>20?' 超过 20 次，请减少关键词、平台或页数。':'只采集并保存，不自动充值。'}`}

async function pollCollection(){
 const job=collectionJob;if(!job)return;const projectId=job.project_id;
 try{
  const next=await api('/api/jobs/'+job.id);
  if(collectionJob?.id!==job.id||next.project_id!==projectId)return;
  collectionJob=next;
  if(state.project?.id===projectId){
   const project=await api('/api/projects/'+projectId);
   if(collectionJob?.id!==job.id)return;
   if(state.project?.id===projectId){state.project=project;if(!state.modal&&!state.composing&&!['quick-query','search-input'].includes(document.activeElement?.id))render()}
  }
  if(next.run.status==='running')collectionPoll=setTimeout(pollCollection,1600);
  else if(state.project?.id===projectId){
   if(state.page==='research')quick.message=`采集结束：新增 ${next.run.imported} 条，异常 ${next.run.errors.length} 项。${next.run.kind==='keywords'?'下一步：选择洞察内容。':'下一步：选择相关内容采评论。'}`;
   toast(`采集结束：新增 ${next.run.imported} 条，异常 ${next.run.errors.length} 项`);
   if(!state.modal&&!state.composing&&!['quick-query','search-input'].includes(document.activeElement?.id))render();
  }
 }catch(error){if(collectionJob?.id===job.id&&state.project?.id===projectId)toast(error.message+'；已保存结果可重新打开项目查看')}
}
function collectionDetail(r){modal('采集任务详情',`<p>${esc(r.source)} · ${date(r.created_at)} · ${esc(r.status)}</p><div class="code">请求：${r.requests} / ${r.request_limit}\n成功页：${r.pages}\n返回有效记录：${r.requested}\n新增：${r.imported} · 重复：${r.duplicates}\n${esc(r.note||'')}</div><p class="caption">每页采集时间随记录保存；请求游标、账号信息与密钥不写入项目。费用按供应商账单为准。</p>${keywordRoundsHtml(r)}<div class="table-wrap"><table><tr><th>平台 / 关键词 / 内容</th><th>页</th><th>HTTP</th><th>结果</th></tr>${(r.page_results||[]).map(x=>`<tr><td>${esc(PLATFORM_LABELS[x.platform]||r.platform)} · ${esc(x.original_query||x.query)}<div class="secondary">${esc(x.query)} ${esc(x.post_id)}${x.round?' · 第 '+esc(x.round)+' 轮 · '+esc(({seed:'根词',az:'A～Z',prefix:'意图前缀',suffix:'意图后缀',suggestion:'联想词递归'})[x.expansion]||x.expansion):''}${x.parent_query?'<br>上层查询：'+esc(x.parent_query):''}</div></td><td>${x.page}</td><td>${x.http??'未收到'}</td><td>${x.error?esc(x.error):`返回 ${x.returned}，新增 ${x.imported}，重复 ${x.duplicates}，无正文等跳过 ${x.skipped}`}</td></tr>`).join('')}</table></div>${r.errors.length?`<p class="error-inline">${r.errors.map(x=>esc(x.reason)).join('<br>')}</p>`:''}`,button('关闭','close'),true)}
async function collectAction(action,el){switch(action){
 case'help':closeModal();goto('guide');return true;
 case'open-search':collectModal('posts');return true;
 case'collect-keywords':collectModal('keywords');return true;
 case'keyword-search':{const k=state.project.keywords.find(x=>x.id===el.dataset.id);collectModal('posts',k.text,k.platform||'tiktok');return true}
 case'selected-search':{const ks=state.project.keywords.filter(x=>state.selected.has(x.id));collectModal('posts',ks.map(x=>x.text).join('\n'),[...new Set(ks.map(x=>x.platform).filter(x=>PLATFORM_NAMES[x]))]);return true}
 case'collect-selected':{const rows=state.project.posts.filter(x=>state.selected.has(x.id));if(!rows.length)throw Error('请先选择内容');collectModal('reviews','',[...new Set(rows.map(x=>x.platform))],rows.map(x=>x.id));return true}
 case'start-collection':{el.disabled=true;try{const body={revision:state.project.revision,kind:collectionKind,platforms:collectPlatforms(),pages:Number(document.querySelector('#collect-pages').value),queries:(document.querySelector('#collect-queries')?.value||'').split('\n'),post_ids:collectionPostIds,...(collectionKind==='keywords'?keywordRequestBody(readKeywordControls('collect')):{})};collectionJob=await api('/api/projects/'+state.project.id+'/collect',body);closeModal();if(collectionKind==='posts'&&body.platforms.length===1&&body.platforms[0]==='amazon'){goto('products')}else if(state.page==='research'){quick.tab=collectionKind;render()}else{if(collectionKind==='keywords')quick.tab='keywords';goto(collectionKind==='keywords'?'research':'posts')}clearTimeout(collectionPoll);await pollCollection()}finally{el.disabled=false}return true}
 case'cancel-collection':await api('/api/jobs/'+collectionJob.id+'/cancel',{});toast('已请求停止；当前请求返回后保存结果，不再发起后续请求');return true;
 case'collection-detail':collectionDetail(collectionJob.run);return true;
 case'post-detail':{const p=state.project.posts.find(x=>x.id===el.dataset.id);modal('内容原文',`<h2>${esc(p.title)}</h2><p style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(p.body||'接口未提供正文')}</p><h3>中文翻译</h3><p class="translation-preview">${esc(p.translation||'尚未翻译，可在内容列表点击「翻译内容」。')}</p><div class="callout">${PLATFORM_LABELS[p.platform]} · ${esc(p.market_scope)}<br>搜索词：${esc(p.query)}<br>采集时间：${date(p.collected_at)} · ${external(p.source_url,'打开原帖')}</div>`,button('查看评论','post-comments','chat','',`data-id="${esc(p.id)}"`)+button('采集此帖评论','collect-one','','primary',`data-id="${esc(p.id)}"`));return true}
 case'collect-one':{const p=state.project.posts.find(x=>x.id===el.dataset.id);collectModal('reviews','',p.platform,[p.id]);return true}
 case'post-comments':{const rows=state.project.reviews.filter(r=>r.post_id===el.dataset.id);modal('已保存的评论原文',rows.map(reviewBlock).join('')||'<p>暂无评论样本。采集后可在此阅读。</p>',button('关闭','close')+button('采集此帖评论','collect-one','chat','primary',`data-id="${esc(el.dataset.id)}"`)+button('翻译此帖评论','translate-reviews','','',`data-post-id="${esc(el.dataset.id)}" ${rows.length?'':'disabled'}`)+button('选择洞察内容','ai-insights','arrow',''),true);return true}
 case'sources':await connectionsModal();return true;
 case'run':{const r=state.project.runs.find(x=>x.id===el.dataset.id);if(r?.mode==='collection'){collectionDetail(r);return true}if(r?.mode==='seller'){modal('卖家精灵查询记录',`<p>${esc(r.original_query)} → ${esc(r.query)}</p><p>完成 1 页；返回 ${r.requested} 条，新增 ${r.imported} 条，重复 ${r.duplicates} 条。</p><p class="caption">来源：卖家精灵 MCP · ${date(r.created_at)}。销量为第三方父体估算。</p>`,button('关闭','close'));return true}return false}
 default:return false;
}}
document.addEventListener('input',e=>{if(e.target.id==='collect-queries'||e.target.id==='collect-keyword-limit')updateBudget()});
document.addEventListener('change',e=>{if(e.target.name==='collect-keyword-mode'){refreshKeywordControls('collect');updateBudget()}if(e.target.id==='collect-keyword-rounds'||e.target.id==='collect-keyword-limit')updateBudget();if(e.target.name==='collect-platform'||e.target.id==='collect-pages')updateBudget()});
