// The report and its standalone export use the same styles and chart renderer.
const REPORT_VISUAL_STYLES = `
.report-document{--report-accent:#2463ad;--report-ink:#24282d;--report-muted:#737c87;--report-line:#e7e9ec;color:var(--report-ink);font:14px/1.85 -apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif;max-width:1080px;margin:0 auto;text-align:left}
.report-document *{box-sizing:border-box}.report-document-simple{max-width:820px}.report-document h2,.report-document h3,.report-document h4,.report-document p{margin:0}.report-document p{overflow-wrap:anywhere;white-space:pre-wrap}.report-document a{color:var(--report-accent)}
.report-document .report-cover{padding:32px 0 34px;border-bottom:1px solid var(--report-line);margin-bottom:30px}.report-cover .report-kicker{font-size:11px;letter-spacing:2px;color:var(--report-accent);margin-bottom:14px}.report-document .report-cover h2{font-size:32px;line-height:1.4;letter-spacing:-.8px;max-width:880px}.report-cover>p{color:var(--report-muted);max-width:790px;margin-top:14px}.report-cover .report-cover-status{font-size:12px;margin-top:22px}
.report-document .report-lead{margin:22px 0 30px;padding:22px 25px;background:#f4f7fb;border-left:3px solid var(--report-accent);border-radius:0 8px 8px 0}.report-lead>span{font-size:11px;letter-spacing:1px;color:var(--report-accent)}.report-lead>p{font-size:18px;line-height:1.85;margin-top:9px}.report-lead .report-lead-basis{font-size:11px;color:var(--report-muted);margin-top:10px}
.report-document .insight-report-layout{display:grid;grid-template-columns:138px minmax(0,820px);gap:38px;align-items:start}.report-document .insight-toc{position:sticky;top:144px;border:0;padding:4px 0}.insight-toc>strong{font-size:11px;color:var(--report-muted);display:block;margin-bottom:14px}.report-document .insight-toc a{display:block;padding:9px 10px;border-left:2px solid var(--report-line);color:var(--report-muted);font-size:12px;text-decoration:none}.report-document .insight-toc a:hover{color:var(--report-accent);background:#f4f7fb;border-color:var(--report-accent)}.insight-toc a span{display:block}.insight-toc a small{font-size:10px;color:#9aa1a9}
.report-document .insight-chapter{padding:0 0 34px;margin:0 0 38px;border:0;border-bottom:1px solid var(--report-line);scroll-margin-top:148px}.report-document .insight-chapter>.section-head{display:flex;align-items:start;justify-content:space-between;gap:18px;margin:0 0 12px}.report-document .section-head h2{font-size:23px;line-height:1.5;margin:5px 0 0}.report-document .eyebrow{font-size:10px;letter-spacing:1px;color:var(--report-muted)}.report-document .report-summary{font-size:15px;line-height:1.9;margin:18px 0 24px;color:#515964}.report-document .insight-part{margin:26px 0}.report-document .insight-part:empty{display:none}.report-document .insight-part h3{font-size:18px;margin:0 0 14px}.report-document .insight-part h4{font-size:14px;margin:0 0 10px}.report-document .insight-part h5,.report-document .insight-part h6{font-size:13px;margin:0 0 8px}.report-document .insight-part>.insight-part{margin:16px 0}.report-document .insight-point{margin:10px 0 18px}.report-document .insight-point>p{margin:5px 0 7px}.report-document .basis{font-size:10px;color:var(--report-muted);border:0;padding:0}.report-document .basis-evidence{color:#527566}.report-document .basis-unknown{color:#8a734e}.report-document .validation{font-size:12px;color:var(--report-muted);margin:8px 0}.report-document .validation strong{font-weight:500}.report-document .caption,.report-document .report-meta{font-size:12px;color:var(--report-muted);line-height:1.75}.report-document .evidence-refs{display:none}.report-document .report-evidence-link{display:inline-block;font-size:11px;color:var(--report-muted);text-decoration:underline;text-underline-offset:3px;margin:2px 0 5px}
.report-document details{margin:16px 0}.report-document summary{cursor:pointer;font-size:12px;color:var(--report-muted);padding:8px 0;list-style:none}.report-document summary::-webkit-details-marker{display:none}.report-document summary:before{content:'＋';margin-right:8px}.report-document details[open]>summary:before{content:'－'}.report-document .report-method,.report-document .report-details{border-top:1px solid var(--report-line);padding-top:8px}.report-document .report-method>div{padding:10px 0 0}.report-document .insight-limitations{background:#f7f8fa;border-radius:6px;padding:8px 14px;font-size:12px}.report-document .insight-limitations summary{padding:4px 0}.report-document ul{padding-left:20px}.report-document li{margin:6px 0}.report-document blockquote{margin:14px 0;padding:12px 18px;background:#f7f8fa;border-left:2px solid #bdc9d8;border-radius:0 6px 6px 0}.report-document blockquote p{font-size:15px}
.report-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-top:1px solid var(--report-line);border-bottom:1px solid var(--report-line);padding:21px 0;margin:18px 0 24px;gap:16px}.report-metric strong{display:block;font-size:31px;font-weight:550;line-height:1.25;letter-spacing:-1px;font-variant-numeric:tabular-nums}.report-metric span{font-size:11px;color:var(--report-muted);display:block;margin-top:8px}.report-metric small{font-size:10px;color:var(--report-muted)}
.report-distribution{margin:18px 0 26px}.report-distribution figcaption{font-size:12px;color:var(--report-muted);margin-bottom:17px}.report-bar-row{display:grid;grid-template-columns:126px minmax(30px,1fr) 80px;gap:14px;align-items:center;margin:15px 0;font-size:12px}.report-bar-row .bar-name{line-height:1.5}.report-bar-row .bar-name small{display:block;color:var(--report-muted);font-size:10px}.report-bar-track{height:9px;background:#eef0f3;border-radius:3px;overflow:hidden}.report-bar-fill{height:100%;background:#aebed1;border-radius:3px}.report-bar-row.is-largest .report-bar-fill{background:var(--report-accent)}.report-bar-value{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}.report-bar-value small{color:var(--report-muted);font-size:10px;margin-left:7px}.report-chart-note{font-size:11px;color:var(--report-muted);margin:12px 0}.report-emotion-track{display:flex;overflow:hidden;border-radius:5px;height:16px;background:#eef0f3;gap:2px;margin:18px 0}.report-emotion-track>i{min-width:0;display:block}.report-emotion-legend{display:flex;gap:14px 24px;flex-wrap:wrap;font-size:12px}.report-emotion-legend>span{display:flex;gap:7px;align-items:center}.report-emotion-legend i{width:7px;height:7px;border-radius:2px;display:inline-block}.report-emotion-legend small{font-size:11px;color:var(--report-muted)}.report-empty-chart{padding:20px 0;color:var(--report-muted);font-size:12px;border-bottom:1px solid var(--report-line)}
.report-theme-list{margin:14px 0}.report-theme{display:grid;grid-template-columns:34px minmax(0,1fr) 58px;gap:12px;padding:17px 0;border-bottom:1px solid var(--report-line)}.report-theme .theme-index{font-size:11px;color:var(--report-muted);padding-top:3px}.report-theme h4{font-size:15px!important;margin:0 0 7px!important}.report-theme p{font-size:13px;color:#626c78}.report-theme .theme-count{text-align:right;font-size:22px;font-variant-numeric:tabular-nums;line-height:1.4}.theme-count small{display:block;font-size:10px;color:var(--report-muted)}.report-theme .insight-point{margin:0}.report-theme .validation{font-size:11px}
.report-persona{padding:26px 0 20px;border-top:1px solid var(--report-line);margin:24px 0}.report-persona-head{display:flex;align-items:flex-start;gap:14px}.report-persona-index{color:var(--report-accent);font-size:12px;margin-top:5px;font-variant-numeric:tabular-nums}.report-persona-title{flex:1;min-width:0}.report-document .report-persona h3{font-size:21px;line-height:1.5;margin:0}.report-persona .persona-one-line{margin:10px 0 18px;font-size:15px;color:#626c78}.persona-priority{font-size:11px;background:#f0f4f9;color:#4d6d94;border-radius:4px;padding:3px 8px;white-space:nowrap}.persona-need{padding:14px 18px;background:#f7f8fa;border-radius:7px;font-size:14px}.persona-need small{display:block;font-size:10px;color:var(--report-muted);margin-bottom:5px}.report-document .persona-details>summary{color:var(--report-accent);padding:12px 0}.report-document .persona-details .insight-part{margin:22px 0}.report-document .persona-attributes{display:grid;grid-template-columns:1fr 1fr;column-gap:30px;row-gap:12px}.report-document .persona-attributes>.insight-part{margin:0;border-top:1px solid var(--report-line);padding-top:14px}.persona-attributes h5{color:var(--report-muted);font-weight:500}.persona-attributes .insight-point>p{font-size:13px}.report-document .report-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 26px}.report-document .report-detail-grid>.insight-part{margin:12px 0}.report-document .report-details .finding{padding:16px 0;border-bottom:1px solid var(--report-line)}.report-document .report-details .finding h3{font-size:11px;color:var(--report-muted);overflow-wrap:anywhere}.report-document .report-details .finding p{font-size:12px;margin:6px 0}
.report-document table{width:100%;border-collapse:collapse;font-size:12px}.report-document td,.report-document th{text-align:left;vertical-align:top;border-bottom:1px solid var(--report-line);padding:11px 12px;white-space:pre-wrap;overflow-wrap:anywhere}.report-document .table-wrap{overflow-x:auto}.report-document .report-next{padding:18px 20px;background:#f6f8fb;border-radius:8px}.report-document .report-next h3{font-size:15px}.report-document .report-next .insight-point:last-child{margin-bottom:0}.report-document .report-meta{margin:5px 0}
.product-direction{padding:24px 0;border-bottom:1px solid var(--report-line)}.product-direction-heading{display:flex;align-items:start;gap:13px}.product-direction-heading>div{flex:1}.product-direction-heading h4{font-size:19px!important;margin:0 0 5px!important}.product-direction-heading p{font-size:12px;color:var(--report-muted)}.product-direction-actions{display:flex;gap:14px;flex-wrap:wrap;align-items:center;margin-top:18px}.product-checks{background:#f7f8fa;padding:14px 18px;border-radius:7px;margin:16px 0}.product-checks strong{font-size:12px;font-weight:500}.product-checks ul{margin:6px 0;font-size:13px}.product-direction>.insight-part{margin:18px 0}
@media(max-width:1100px){.report-document .insight-report-layout{grid-template-columns:minmax(0,820px);gap:22px}.report-document .insight-toc{position:static;display:flex;flex-wrap:wrap;gap:4px 12px;padding-bottom:16px;border-bottom:1px solid var(--report-line)}.insight-toc>strong{width:100%;margin-bottom:5px}.report-document .insight-toc a{padding:4px 0;border:0}.insight-toc a small{display:none}.report-document .insight-toc a span{display:inline}}
@media(max-width:600px){.report-document .report-cover{padding:18px 0 24px}.report-document .report-cover h2{font-size:26px}.report-document .report-lead{padding:18px}.report-lead>p{font-size:16px}.report-metrics{grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.report-metric strong{font-size:28px}.report-bar-row{grid-template-columns:92px minmax(30px,1fr) 66px;gap:8px}.report-bar-value small{margin-left:3px}.report-document .persona-attributes,.report-document .report-detail-grid{grid-template-columns:1fr}.report-document .report-persona h3{font-size:18px}.report-persona-head{gap:9px}.report-document .insight-chapter>.section-head{flex-wrap:wrap}.report-theme{grid-template-columns:25px minmax(0,1fr) 42px;gap:8px}.report-document .report-cover-status{font-size:11px}}
@media print{.report-document{max-width:none;font-size:11pt}.report-document .insight-report-layout{display:block}.report-document .insight-toc{display:none}.report-document .report-cover h2{font-size:25pt}.report-document .insight-chapter{break-before:auto;margin:24px 0}.report-persona,.report-distribution,.report-metrics,.report-theme,blockquote{break-inside:avoid}.report-persona{break-inside:auto}.report-persona-head,.persona-need,.persona-attributes>.insight-part{break-inside:avoid}.report-persona-head{break-after:avoid}.report-document .report-bar-fill,.report-emotion-track>i{print-color-adjust:exact;-webkit-print-color-adjust:exact}.report-document button{display:none}.report-document .report-details{display:none}.report-document .persona-details summary{display:none}}
`;

function reportNumber(value){return typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null}
function keywordStatsRows(r,field){return r.report?.stats?.[field]||Object.entries((r.report?.items||[]).filter(x=>x.valid).reduce((out,x)=>{const key=x[field==='journey'?'stage':field];if(key)out[key]=(out[key]||0)+1;return out},{})).map(([name,count])=>({name,count}))}
function reportDistribution(rows,{style='bars',total,label='样本分类分布'}={}){
 const values=(rows||[]).map(x=>({...x,count:reportNumber(x.count)}));
 if(!values.length)return `<div class="report-empty-chart">${esc(label)}：暂无分布数据。</div>`;
 const sum=values.reduce((n,x)=>n+(x.count??0),0),known=values.every(x=>x.count!==null);
 const denominator=reportNumber(total)??(known?sum:null),consistent=denominator!==null&&sum<=denominator;
 const percent=n=>consistent&&denominator>0&&n!==null?(n/denominator*100).toFixed(1).replace(/\.0$/,'')+'%':null;
 const max=Math.max(0,...values.map(x=>x.count??0)),scope=denominator===null?'范围未提供':`${denominator} 条样本关键词`;
 const notes=`${scope}；按记录计数，不代表人数、市场份额或转化率。${!known?'部分分类数量未提供。':''}${consistent&&denominator>sum?'其余 '+(denominator-sum)+' 条未计入以上分类。':''}${!consistent&&denominator!==null?'分类计数与总数不一致，暂不展示占比。':''}`;
 const labels={WHAT:'产品与信息',WHO:'使用人群',WHERE:'地点与渠道',WHEN:'时间与时机',WHY:'原因与顾虑',HOW:'方法与解决办法',A1:'认知',A2:'了解',A3:'比较',A4:'决策／解疑',A5:'购买'};
 const colors={'正向':'#7f9e91','负向':'#b98c80','中性':'#a6b8cb'};
 const color=(x,i)=>colors[x.name]||['#7f9e91','#b98c80','#a6b8cb','#899aaa'][i%4];
 let body;
 if(style==='emotion'){
  body=`<div class="report-emotion-track" aria-hidden="true">${values.filter(x=>x.count>0).map((x,i)=>`<i style="width:${consistent&&denominator>0?x.count/denominator*100:0}%;background:${color(x,i)}"></i>`).join('')}</div><div class="report-emotion-legend">${values.map((x,i)=>`<span data-count="${x.count??''}"><i style="background:${color(x,i)}"></i>${esc(x.name)} <b>${x.count??'未提供'}</b>${percent(x.count)?`<small>${percent(x.count)}</small>`:''}</span>`).join('')}</div>`;
 }else{
  body=values.map(x=>`<div class="report-bar-row ${x.count===max&&max>0?'is-largest':''}" data-count="${x.count??''}"><span class="bar-name">${esc(x.name)}${labels[x.name]?`<small>${labels[x.name]}</small>`:''}</span><div class="report-bar-track" aria-hidden="true"><div class="report-bar-fill" style="width:${max&&x.count!==null?x.count/max*100:0}%"></div></div><span class="report-bar-value">${x.count??'未提供'}${percent(x.count)?`<small>${percent(x.count)}</small>`:''}</span></div>`).join('');
 }
 return `<figure class="report-distribution" data-total="${denominator??''}"><figcaption>${esc(label)}</figcaption>${body}<p class="report-chart-note">${esc(notes)}</p></figure>`;
}
function reportMetrics(values){return `<div class="report-metrics">${values.map(([label,value,note])=>`<div class="report-metric"><strong>${esc(value??'—')}</strong><span>${esc(label)}</span>${note?`<small>${esc(note)}</small>`:''}</div>`).join('')}</div>`}
function reportReadingOrder(r){const order=['summary','clean','intent','audience','comments','notes','topics'];return order.filter(key=>r.report?.modules?.[key])}
