const quick={query:'',platform:'xhs',platforms:['xhs','tiktok','reddit'],filter:'all',tab:'keywords',pages:1,keyword_mode:'quick',rounds:1,request_limit:200,busy:false,message:''};
const PLATFORM_NAMES={xhs:'小红书',tiktok:'TikTok',reddit:'Reddit',amazon:'Amazon'};
function selectedPlatforms(){return quick.platforms.length?quick.platforms:[]}
function platformPicker(name,selected){return `<div class="platform-picker" role="group" aria-label="调研平台，可多选">${Object.entries(PLATFORM_NAMES).map(([id,label])=>`<label><input type="checkbox" name="${name}" value="${id}" ${selected.includes(id)?'checked':''}><span>${label}</span></label>`).join('')}</div>`}
function syncQuickProject(){const p=state.project;if(!p||p.demo)return;quick.query=p.keyword;const runs=[...p.runs].reverse();const r=runs.find(x=>x.mode==='collection'&&x.kind==='keywords')||runs.find(x=>x.mode==='seller'||x.mode==='collection');quick.keyword_mode=r?.keyword_mode||'quick';quick.rounds=r?.rounds||1;quick.request_limit=r?.keyword_mode&&r.keyword_mode!=='quick'?r.request_limit:200;if(r){quick.platforms=r.platforms?.length?r.platforms:[r.mode==='seller'?'amazon':r.platform];quick.platforms=quick.platforms.filter(x=>PLATFORM_NAMES[x]);if(!quick.platforms.length)quick.platforms=['xhs'];quick.platform=quick.platforms[0];quick.tab=r.kind==='posts'&&quick.platforms.length===1&&quick.platforms[0]==='amazon'?'products':r.kind}quick.filter='all';quick.message='';}
function quickRows(){const p=state.project;if(!p)return [];return (p[quick.tab]||[]).filter(r=>(quick.filter==='all'||r.platform===quick.filter)&&[r.text,r.title,r.body,r.translation].filter(Boolean).join(' ').toLowerCase().includes(state.query.toLowerCase()))}
function research(){const p=state.project,rows=quickRows();const active=quick.busy||(collectionJob?.project_id===p?.id&&collectionJob?.run.status==='running');const amount=selectedPlatforms().length;const social=selectedPlatforms().filter(x=>x!=='amazon').length,translate=/[\u3400-\u9fff]/.test(quick.query)&&selectedPlatforms().some(x=>x!=='xhs')?1:0,mcp=selectedPlatforms().includes('amazon')?1:0;return head('关键词洞察','从搜索词与评论里找用户需求，形成选品方向，再核对竞品数据。')+flowNav('research')+`<section class="quick-input"><label for="quick-query">产品关键词</label><input id="quick-query" placeholder="中文也可以，例如：宠物饮水机" value="${esc(quick.query)}" maxlength="300"><div class="quick-options"><div><span class="field-label">调研平台 · 可多选</span>${platformPicker('quick-platform',selectedPlatforms())}</div><details><summary>内容采集选项</summary><label for="quick-pages">内容每词采集页数</label><select id="quick-pages">${[1,2,3,5].map(n=>`<option value="${n}" ${quick.pages===n?'selected':''}>${n} 页</option>`).join('')}</select></details></div>${keywordControls('quick',quick)}<div class="actions">${button(active?'采集中…':'采集关键词','quick-keywords','search','primary',active?'disabled':'')}${button('搜索内容与商品','quick-posts','', '',active?'disabled':'')}</div><p class="caption" id="quick-keyword-budget">已选 ${amount} 个平台。${esc(keywordBudgetText(quick,[quick.query],selectedPlatforms()))} 搜内容最多 ${social*quick.pages+translate+mcp} 次请求；内容和评论仍最多 20 次。每个 Amazon 查询最多 10 条。</p>${quick.message?`<p class="quick-message" role="status">${esc(quick.message)}</p>`:''}</section>${jobView()}${aiProgress()}${p&&!p.demo?`${nextStep()}<div class="quick-result-head"><div class="actions">${[['keywords','关键词',p.keywords.length],['posts','内容',(p.posts||[]).length],['products','竞品',p.products.length],['reviews','评论',p.reviews.length]].map(([k,v,n])=>button(v+' '+n,'quick-tab','','small '+(quick.tab===k?'subtle':''),`data-tab="${k}"`)).join('')}</div>${button('翻译成中文','translate-current','','small',rows.length&&quick.tab!=='products'?'':'disabled')}</div><div class="toolbar"><div class="search">${icon('search')}<input id="search-input" aria-label="筛选已采集资料" placeholder="筛选原文或中文" value="${esc(state.query)}"></div></div><div class="platform-filters">${[['all','全部平台'],...Object.entries(PLATFORM_NAMES)].map(([k,v])=>button(v,'quick-filter','','small '+(quick.filter===k?'subtle':''),`data-platform="${k}"`)).join('')}</div>${quickResults(rows)}`:empty('输入产品名，再选平台开始','采集完成后，可直接生成关键词报告，并继续采集内容和评论。')}`}
function nextStep(){const p=state.project;if(!p)return '';const ready=p.keywords.length||p.posts?.length||p.reviews.length;return `<section class="next-step"><div><span class="eyebrow">下一步</span><h3>${ready?'资料已保存，选择这次要洞察什么':'先采关键词，或搜索相关内容'}</h3><p>${ready?'优先看人群画像、搜索意图与评论需求，形成产品方向，再去卖家精灵核对商品与竞品数据；每项结果单独保存。':'每一步结果都会保存在当前项目。'}</p></div><div class="actions">${ready?button('选择洞察内容','view-insights','arrow','primary'):button('采集关键词','quick-keywords','search','primary')}</div></section>`}

function quickResults(rows){if(!rows.length)return empty('这里还没有结果','切换平台筛选，或在上方开始采集。');if(quick.tab==='reviews')return rows.map(reviewBlock).join('');if(quick.tab==='keywords')return keywordTable(rows);if(quick.tab==='products')return `<div class="table-wrap"><table><tr><th>商品</th><th>价格 / 评分</th><th>操作</th></tr>${rows.map(r=>`<tr><td>${esc(r.title)}<div class="secondary">${external(r.source_url)}</div></td><td>${money(r)}<div class="secondary">${r.rating??'—'} / 5</div></td><td>${button('采商品评论','seller-reviews','','small',`data-id="${esc(r.id)}"`)} ${button(r.candidate?'已加入候选':'加入候选','candidate','','small',`data-id="${esc(r.id)}"`)}</td></tr>`).join('')}</table></div>`;return `<div class="selection-bar"><span>已选 ${state.selected.size} 条内容，可跨平台选择</span>${button('采集所选评论','collect-selected','chat','small',state.selected.size?'':'disabled')}</div><div class="table-wrap"><table class="quick-posts"><thead><tr><th><input type="checkbox" id="select-all" aria-label="选择当前内容"></th><th>相关内容</th><th>已采评论</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td><input type="checkbox" data-select="${esc(r.id)}" ${state.selected.has(r.id)?'checked':''} aria-label="选择 ${esc(r.title)}"></td><td><button class="post-title" data-action="post-detail" data-id="${esc(r.id)}">${esc(r.title)}</button>${r.translation?`<div class="translation-preview">${esc(r.translation)}</div>`:''}<div class="secondary">${esc(PLATFORM_NAMES[r.platform])} · ${esc(r.query)} · ${external(r.source_url,'原帖')}</div></td><td>${state.project.reviews.filter(c=>c.post_id===r.id).length}</td><td>${button('看评论','post-comments','','small',`data-id="${esc(r.id)}"`)}</td></tr>`).join('')}</tbody></table></div>`}
async function quickStart(kind,reuseProject=false){if(quick.busy)return;const query=quick.query.trim(),platforms=selectedPlatforms();if(!query)throw Error('先输入一个产品关键词，中文也可以');if(!platforms.length)throw Error('请至少选择一个平台');if(kind==='keywords')Object.assign(quick,readKeywordControls('quick'));quick.busy=true;quick.message='正在创建多平台采集任务…';render();try{if(!state.project||state.project.demo||(!reuseProject&&state.project.keyword!==query)){state.project=await api('/api/projects',{name:query+' · 需求调研',keyword:query});location.hash='research?project='+state.project.id}state.selected.clear();quick.tab=kind==='posts'&&platforms.length===1&&platforms[0]==='amazon'?'products':kind;quick.filter='all';collectionJob=await api('/api/projects/'+state.project.id+'/collect',{revision:state.project.revision,kind,platforms,queries:[query],pages:kind==='keywords'?1:quick.pages,...(kind==='keywords'?keywordRequestBody(quick):{})});quick.message='各平台会逐项保存，失败的平台不会影响其他结果。';clearTimeout(collectionPoll);await pollCollection()}catch(error){quick.message=error.message;throw error}finally{quick.busy=false;render()}}
async function researchAction(action,el){switch(action){
case'quick-posts':await quickStart('posts');return true;
case'query-products':collectModal('posts',state.project.keyword,['amazon']);return true;
case'quick-keywords':await quickStart('keywords');return true;
case'quick-tab':quick.tab=el.dataset.tab;state.query='';state.selected.clear();render();return true;
case'quick-filter':quick.filter=el.dataset.platform;render();return true;
case'quick-word':{const k=state.project.keywords.find(x=>x.id===el.dataset.id);collectModal('posts',k.text,k.platform||'xhs');return true}
case'quick-insights':goto('insights');return true;
case'seller-connect':await connectionsModal();return true;
case'seller-perform-connect':case'tikhub-perform-connect':{const seller=action==='seller-perform-connect';const input=document.querySelector(seller?'#seller-key':'#tikhub-key');const status=document.querySelector(seller?'#seller-connection-status':'#tikhub-connection-status');const persist=document.querySelector(seller?'#save-seller':'#save-tikhub').checked;el.disabled=true;status.textContent='正在验证连接…';try{const result=await api(seller?'/api/sellersprite/connect':'/api/sources/connect',{key:input.value,persist,...(!seller?{base_url:document.querySelector('#tikhub-base').value}:{})});input.value='';status.textContent=(seller?`已连接，发现 ${result.tool_count} 个工具`:'连接验证成功（HTTP 200）')+(persist?'；已保存到本机，重启自动读取。':'；仅本次服务有效。');toast(seller?'卖家精灵已连接':'TikHub 已连接')}catch(error){status.textContent=error.message;throw error}finally{el.disabled=false}return true}
case'device-guide':closeModal();modal('在另一台设备使用',`<ol class="guide-list"><li>在另一台设备获取工作台源码，由 Codex 按 README 启动 team_start.py，或双击对应系统的「打开工作台」文件。</li><li>在「报告与选品」导出项目包，到另一台设备导入，即可继续查看原文、译文和报告。</li><li>每台设备在「数据源与能力」配置获授权的数据源连接；Git 不会同步密钥和业务数据。</li><li>新增分析使用该设备已登录的 Codex。成员各自的项目副本不会自动实时合并。</li></ol>`,button('返回连接设置','seller-connect'));return true;
case'seller-reviews':{el.disabled=true;try{state.project=await api('/api/projects/'+state.project.id+'/seller-collect',{revision:state.project.revision,kind:'reviews',product_id:el.dataset.id});quick.tab='reviews';quick.message=`新增 ${state.project.runs.at(-1).imported} 条 Amazon 评价`;render()}finally{el.disabled=false}return true}
default:return false;
}}
function updateQuickKeywordBudget(){const target=document.querySelector('#quick-keyword-budget');if(target)target.textContent=keywordBudgetText(quick,[quick.query],selectedPlatforms())}
document.addEventListener('input',e=>{if(e.target.id==='quick-query'){quick.query=e.target.value;updateQuickKeywordBudget()}if(e.target.id==='quick-keyword-limit'){quick.request_limit=Number(e.target.value);updateQuickKeywordBudget()}});
document.addEventListener('change',e=>{if(e.target.name==='quick-platform'){quick.platforms=[...document.querySelectorAll('input[name="quick-platform"]:checked')].map(x=>x.value);quick.platform=quick.platforms[0]||'xhs';render()}if(e.target.id==='quick-pages'){quick.pages=Number(e.target.value);render()}if(e.target.name==='quick-keyword-mode'){quick.keyword_mode=e.target.value;quick.rounds=e.target.value==='quick'?1:Math.max(2,quick.rounds);render()}if(e.target.id==='quick-keyword-rounds'){quick.rounds=Number(e.target.value);updateQuickKeywordBudget()}if(e.target.id==='quick-keyword-limit'){quick.request_limit=Number(e.target.value);updateQuickKeywordBudget()}});
document.addEventListener('keydown',e=>{if(e.target.id==='quick-query'&&e.key==='Enter'&&!e.isComposing&&!state.composing){e.preventDefault();quickStart('keywords').catch(x=>toast(x.message))}});

async function connectionsModal(){const [tik,seller,setup,ai]=await Promise.all([api('/api/sources'),api('/api/sellersprite'),api('/api/device-setup'),api('/api/ai')]);const check=(id,backend)=>`<label class="caption"><input type="checkbox" id="${id}" ${backend?'checked':'disabled'}>保存在这台设备${backend?'（'+esc(backend)+'）':'（此系统暂不支持，仅本次连接）'}</label>`;modal('数据源与设备设置',`<p>${esc(setup.note||'新设备可在这里连接数据源。')}</p><p class="caption">地址已内置；验证成功后再保存到本机。</p><section class="flat-section"><h3>卖家精灵 · Amazon 数据</h3><p id="seller-connection-status" role="status">${seller.connected?'当前已连接，发现 '+seller.tool_count+' 个工具':seller.configured?'本机有凭据，首次查询会自动连接':'这台设备尚未连接'}${seller.saved?' · 已保存到本机':''}</p><div class="field"><label for="seller-key">MCP 完整链接或密钥</label><input id="seller-key" type="password" autocomplete="off" maxlength="2500" placeholder="粘贴「复制 MCP 链接」的内容；已有连接可留空"></div><div class="actions">${check('save-seller',seller.secure_storage)}${button('验证并连接','seller-perform-connect','','primary')}</div><p class="caption">${external('https://open.sellersprite.com/app/list','打开卖家精灵，复制 MCP 链接')} · 商品、关键词月搜索量、商品评论</p></section><section class="flat-section"><h3>TikHub · 三平台采集</h3><p id="tikhub-connection-status" role="status">${tik.configured?'本机凭据可读取，点击按钮可验证':'这台设备尚未连接'}${tik.saved?' · 已保存到本机':''}</p><div class="field"><label for="tikhub-key">TikHub API Key</label><input id="tikhub-key" type="password" autocomplete="off" maxlength="1500" placeholder="粘贴 API Key；本机已有凭据可留空"></div><div class="field"><label for="tikhub-base">网络区域</label><select id="tikhub-base"><option value="https://api.tikhub.dev" ${tik.base_url==='https://api.tikhub.dev'?'selected':''}>中国大陆</option><option value="https://api.tikhub.io" ${tik.base_url==='https://api.tikhub.io'?'selected':''}>海外</option></select></div><div class="actions">${check('save-tikhub',tik.secure_storage)}${button('验证并连接','tikhub-perform-connect','','primary')}</div><p class="caption">${external('https://user.tikhub.io','打开 TikHub，复制 API Key')} · 小红书、TikTok、Reddit 与中文关键词翻译</p></section><section class="flat-section"><h3>本机 Codex · 分析与翻译</h3><p>${ai.available?'已找到本机 Codex；生成报告时使用这台设备的登录与额度。':'这台设备尚未找到 Codex，请先在本机安装并登录。'}</p><p class="caption">${esc(ai.note)}</p></section><p class="caption">不会将密钥写入项目、浏览器存储或报告。首次使用请在这台设备配置获授权的数据源连接；已有连接可留空。关键词分析、需求洞察和中文翻译使用本机 Codex。</p>`,button('另一台设备怎么用','device-guide')+button('完成','close','','primary'),true)}

async function checkDeviceSetup(attempt=0){try{const x=await api('/api/device-setup');if(['receiving','ready','failed'].includes(x.state)&&quick.message!==x.note){quick.message=x.note;if(!state.composing&&!state.modal&&document.activeElement?.id!=='quick-query')render()}if(['idle','receiving'].includes(x.state)&&attempt<40)setTimeout(()=>checkDeviceSetup(attempt+1),3000)}catch{}}
